arch/arm64/boot/dts/freescale/crocodile.dts
drivers/spi/spidev.c

arm64: dts: crocodile: Change ecspi2 compatible to "lgs-crocodile,spi"
spi: spidev: Add compatible for lgs-crocodile spi.
arm64: dts: crocodile: Disable the node micfil to release GPIO

Fix Crocodile spidev_probe warning and disable micfil

---

arch/arm64/boot/dts/freescale/ap20-pt1.dts
arch/arm64/boot/dts/freescale/ap20.dtsi

Add initial support for AP20 PT1:
- Port and adapt common nodes from `dragonstaff.dts` to `ap20.dtsi`
- Introduce new `ap20-pt1.dts` based on `ap20.dtsi` containing fixes for PT1

[leica/5.4-2.1.x-imx/dragonstaff]: Add DTB support for P1

---

arch/arm64/boot/dts/freescale/ap20-pt1.dts

We are going to use model name in test scripts. It was agreed to use common pattern `<name>[-variant]` accross all products for the model name to be easily identified, e.g.: `AP20-PT1`, `AP20-PT2`, `AP20`.

[leica/5.4-2.1.x-imx/dragonstaff]: ap20-pt1: change model name

---

arch/arm64/boot/dts/freescale/ap20.dtsi

Move definitions of all GPIO pads, which are not assigned to any
property `pinctrl`, to group `pinctrl_gpios` and assign it to
`pinctrl-0` of node `iomuxc` in order to initialize the pads.
Without this, the pad control registers are not initialized and contain
their default values.

[leica/5.4-2.1.x-imx/dragonstaff]: ap20: initalize gpio pads

---

arch/arm64/boot/dts/freescale/ap20.dtsi

PMIC configuration of AP20 differs from Variscite downstream
device-tree. Since PMIC is placed on SOM board, we need to align its
configuration in order to avoid undesired effects.

[leica/5.4-2.1.x-imx/dragonstaff]: arm64: dts: ap20: align PMIC configuration with imx8mm-var-dart.dts

---

arch/arm64/boot/dts/freescale/ap20.dtsi

After commit e65b9b09d9a7 ("arm64: dts: ap20: align PMIC configuration with imx8mm-var-dart.dts") irq 87 is incorrectly configured as Level sensitive:
```
$ cat /proc/interrupts:
87: 100001 0 0 0 gpio-mxc 8 Level bd718xx-irq
$ dmesg
[ 66.258482] irq 87: nobody cared (try booting with the "irqpoll" option)
[ 66.265192] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 5.4.134 #1
[ 66.271195] Hardware name: AP20-PT1 (DT)
[ 66.275115] Call trace:
[ 66.277569] dump_backtrace+0x0/0x140
[ 66.281230] show_stack+0x14/0x20
[ 66.284545] dump_stack+0xb4/0x110
[ 66.287946] __report_bad_irq+0x48/0xd4
[ 66.291781] note_interrupt+0x2c4/0x388
[ 66.295616] handle_irq_event_percpu+0x80/0x88
[ 66.300058] handle_irq_event+0x44/0xd8
[ 66.303892] handle_level_irq+0xb4/0x138
[ 66.307814] generic_handle_irq+0x24/0x38
[ …
```

[leica/5.4-2.1.x-imx/dragonstaff]: arm64: dts: ap20: fix pmic interrupt level->edge

---

arch/arm64/boot/dts/freescale/crocodile.dtsi

The product managment confirmed the usage of the RTC wakeup interrupt, so
we need to include it in the device tree.
Signed-off-by: massimo toscanelli <massimo.toscanelli@leica-geosystems.com>

arm64: dts: crocodile: add wakeup rtc

---

arch/arm64/boot/dts/freescale/ap20-pt1-5.dts

Introduce new device tree for PT1.5 based on `ap20.dtsi`.
Signed-off-by: massimo toscanelli <massimo.toscanelli@leica-geosystems.com>

arm64: dts: ap20-pt1-5: add support for AP20-PT1.5

---

arch/arm64/boot/dts/freescale/crocodile.dtsi

Operations on kernel console needs to be atomic - that's why `uart2`
in imx8mm.dtsi does not provide any DMA-properties, since usually this
UART is used as kernel console.
On crocodile `uart3` is used as console.
Remove DMA-properties from node `uart3` and add the specific ones to
`uart2` (which are missing in imx8mm.dtsi).

arm64: dts: crocodile: remove DMA for console

---

arch/arm64/boot/dts/freescale/ap20.dtsi

With this patch, key-code `KEY_POWER` is emitted if GPIO4_IO28 is set to HIGH.
The key-code is handled by systemd's logind and a shutdown is initiated.

arm64: dts: ap20: add node for power GPIO

---

arch/arm64/boot/dts/freescale/ap20.dtsi

In case the connected port-pin on MCU is not initialized, we need to
prevent from a floating signal.
Enable pull-down resistors for pad SAI3_RXFS (GPIO4_IO28) in order to
have a defined signal - the active state of "Power-Off-Signal" is high.

arm64: dts: ap20: enable pull-down resistors for pad SAI3_RXFS

---

Documentation/devicetree/bindings/usb/ci-hdrc-usb2.txt
arch/arm64/boot/dts/freescale/crocodile.dtsi
drivers/usb/chipidea/ci_hdrc_imx.c

If suspended, the USB controller of the IMX8MM cannot wake up
connecting a cable. Therefore, we disable the low power mode for the
USB controller.
We also fix the USB picophy parameters (in crocodile.dtsi), that need to be coherent with the new
samsung-based definitions.
Signed-off-by: Massimo Toscanelli <massimo.toscanelli@leica-geosystems.com>

usb: chipidea: add "ci-disable-lpm"

---

arch/arm64/boot/dts/freescale/crocodile.dtsi

once the measurement has been performed, the DRDY pin is set to high,
and clear after read the measurement the data, if pull is enable, sometimes
the pin can not clean by magnetometer, it cause no rising edge even the
data is ready, then the bufferd reading will be timeout.

arm64: dtsi: crocodile: Disable magnetometer pull resistors

---

arch/arm64/boot/dts/freescale/crocodile.dtsi

In order to shutdown properly, we use the signal from MCU connected to
ONOFF pad. If the signal is set by MCU shorter than 5 seconds, the
interrupt set_pwr_off_irq is raised and input event KEY_POWER is sent.
Refer to https://github.com/hexagon-geo-surv/linux-leica/commit/2d5305a54b955396366e915586eddd0f3a1b5184

arm64: dts: crocodile: enable SNVS power key

---

arch/arm64/boot/dts/freescale/beluga.dts
drivers/spi/spidev.c

UART3 connected to expansion connector on beluga EVK,
Enable the port to connect UART devices.

arm64: dts: beluga: enable uart3

---

arch/arm64/boot/dts/freescale/imx8mp-evk.dts
arch/arm64/boot/dts/freescale/imx8mp.dtsi
drivers/pci/controller/dwc/pci-imx6.c
drivers/phy/freescale/phy-fsl-imx8m-pcie.c
drivers/reset/reset-imx7.c

This is the most minimal patch series for PCIe support on the i.MX8MP.
The patches were once sent to the mailing list as V2 and some conflicts had to be resolved.
I expect that a revised V3 will be sent again in the near future.

Initial PCIe support for i.MX8MP

---

drivers/pci/quirks.c

This patch is required to run the PolarFire FPGA demo on non-x86 platforms (like the i.MX8MP). If the FPGA designer chooses a reasonable value for the PCI class code, this correction is not required for the final PCIe FPGA image.
So, I'm not sure if you want to apply this patch to your kernel or not.

PCI: add class quirk for Microchip DG0756 to fix BAR assignment

---

arch/arm64/boot/dts/freescale/crocodile.dtsi

The UART baudrate in the Bluetooth firmware of uBlox BT/WLAN module
MAYA-W161 on PT1 is set to 3M (while it is 115200 on MAYA-W160).
Without setting IMX8MM_SYS_PLL1_80M as parent, the baudrate of 3M is too
high for the default clock input and the communication with the module
fails.
As baudrate 115200 for MAYA-W160 can also be achieved with
IMX8MM_SYS_PLL1_80M this goes into `crocodile.dtsi`.

arm64: dts: crocodile: uart2: set IMX8MM_SYS_PLL1_80M parent of uart2 clock

---

arch/arm64/boot/dts/freescale/ap20-pt1-5.dts

partly revert commit `7fd8785cf68df835684247f61dabb4f6580d118d`
1. When `trigger_update`, in the first step, a new updater image will be updated on board and set `swu=1` to reboot.
2. The new updater image will call `bootm ${initrd_addr}#${fit_config}` to boot up. but now the fit_config was an older version, it point to `AP20-PT1-5.dtb`. And the updater image is initramfs, it will contain device tree by itself when finding `AP20-PT1-5.dtb`.
So restore `AP20-PT1-5.dtb` here.

arm64: dts: ap20-pt1-5: restore ap20-pt1-5.

---

arch/arm64/boot/dts/freescale/crocodile-rev-b.dts

The crocodile.dtsi should reflect the final board - where access to
GPIO4 and GPIO5 is dedicated to M4 - therefore both nodes are disabled.
In board revision B, all GPIOs are only accessed by A53 - enable them.

arm64: dts: crocodile: enable GPIO4 and GPIO5

---

arch/arm64/boot/dts/freescale/beluga.dts

Enable the USB1, the type c PORT1 connector.
For RNDIS and Mass storage as peripheral.

arm64: dts: beluga: Enable type C port USB1

---

drivers/spi/spidev.c

Add DT compatible string to probe and get spi device nodes.
Signed-off-by: Mamta Shukla <mamta.shukla@leica-geosystems.com>

drivers: spi: add leica compatible entry from dts

---

arch/arm64/boot/dts/freescale/crocodile.dtsi

This reverts commit ab7abfe71812f7fa766ee4d20504cd09fc25d37a.
Enabling open-drain for UART4 TX decreases the high voltage level, leading to an unstable connection. Further, there is no reason to enable it, as the connection was stable before, when open-drain was disabled.

Revert "arm64: dts: crocodile: uart4: set pullups/downs on UART to MCU"

---

arch/arm64/boot/dts/freescale/crocodile-rev-b.dts

Add support to communication with Cortex M4 processor in crocodile-rev-b boards.
This allows to load "dummy" firmwares that do not use any external gpio, but just rpmsg communication for testing purposes.
Signed-off-by: Massimo Toscanelli <massimo.toscanelli@leica-geosystems.com>

arm64: dts: crocodile-rev-b: add m4 support

---

arch/arm/boot/dts/leica_krea.dts

FGPA image version 1.0.1034307 implements Iride Light (Auto Exposure Prototoype): some IP blocks got changed.
Heanse, align the DTS to provide correct HW description.
This partially reverts commit 604682b6f17 ("ARM: dts: leica-krea: align with FPGA image 1022315").

ARM: dts: leica-krea: align with FPGA image 1034307

---

arch/arm64/boot/dts/freescale/crocodile.dtsi

according to the power (sequence) table found in the baseboard schematic (of rev-b)
"stumbled" over this while upstreaming the imx8mm-revb.dts
applied the changes to barebox too, system seems to boot just fine, and hold up under load(?)
$> md5sum /dev/zero & # times 4
$> cat /proc/loadavg 
4.20 4.20 3.61 5/148 519
=> is there "an appropriate" way to verify those limits?
NOTE: not quite sure about the limits of LDO5 = NVCC_SD2 though...
-> please tripple check (-:

arm64: dts: crocodile: pmic: set min/max voltages

---

arch/arm64/boot/dts/freescale/beluga.dts

Enable UART3 on the EXP_CN connector and provide the corresponding pinctrl for testing external UART based modules.

arm64: dts: beluga: add support for UART3

---

drivers/clk/imx/clk-imx8mp.c

Linux frozen after boot M7 without bootargs "clk_ignore_unused",
since clock IMX8MP_CLK_M7_DIV never assigned.
Correct m7 clocksource from IMX8MP_CLK_M7_DIV to IMX8MP_CLK_M7_CORE.

clk: imx8mp: Alias M7 SRC/DIV to M7 CORE

---

arch/arm64/boot/dts/freescale/beluga-uart3.dts
arch/arm64/boot/dts/freescale/beluga.dts

UART3 is also used from co-processor Cortex-M7. To avoid concurrent access we provide the enabling of it as an overlay, which can be applied if co-processor will not be used.
Fixes: dd6ef5c3dfd4 ("arm64: dts: beluga: add support for UART3")

arm64: dts: beluga: move support for UART3 to overlay
